name: flutter_app
description: A complete example of a Flutter app built with flutter_bloc

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^6.0.4

  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  equatable: ^1.2.4
  provider: ^4.3.2+1
  test: ^1.15.3
  bloc_test: ^7.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true