name: master_ci

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/replay_bloc.yaml"
      - "packages/replay_bloc/**"

  pull_request:
    branches:
      - master      

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Format
      run: dartfmt --dry-run --set-exit-if-changed .  
    - name: Run tests
      run: pub run test 
